### ISSUE TITLE
Telescope becomes blank

### ISSUE THREAD

**Issue by joantune** [Shopify/polaris-telescope#8] opened 2018-08-14 11:24 UTC
Hi!

I tried using Telescope 0.9.2 and 0.9.4 together with Sketch 50.2 - and I keep getting a blank page whenever I search for anything - https://pasteboard.co/Hz7DMHc.png

I thought that maybe it's because i'm using an older version of Sketch with a newer version of Telescope - any idea which version I should use or how to further debug the issue? 

Thanks

**Comment by HYPD** [comment] 2018-08-15 19:30
@joantune I've tried to replicate the issue using both the latest version of Sketch and Sketch 50.2 with Telescope 0.9.4. It seems to work fine on my end.

Try these steps:
* Delete the plugin from Sketch, download a new copy and reinstall it
* Clear your browser cache
* Restart your system if you haven't already
* Confirm you can connect to https://polaris.shopify.com using your default OS browser (in this case safari)
* Reinstall Sketch (though not sure how this would help)

**Comment by joantune** [comment] 2018-08-16 12:47
I did all of those - minus reinstalling Sketch - I'll try that one - but first tell me - can I see some kind of debug info on what's happening in Telescope?

Also, I'm running that combo on OS X El Capitan (10.11.6)

**Comment by kaelig** [comment] 2018-09-17 18:59
You could try to [run the plugin locally](https://github.com/Shopify/polaris-telescope/blob/master/CONTRIBUTING.md#how-to-run-locally) and you'll then have debug info via skpm and the sketch console.

Closing as we couldn't reproduce this issue and this is concerning an old version of Sketch (which we're not supporting).

**Closed by kaelig** 2018-09-17 18:59 UTC
